# Generated by Django 5.2 on 2025-04-22 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicebookings', '0005_servicetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_type', to='servicebookings.servicetype'),
        ),
    ]
