# Generated by Django 5.2 on 2025-04-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicebookings', '0006_alter_servicerecord_service_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerecord',
            old_name='service_type',
            new_name='service_type_id',
        ),
    ]
