# Generated by Django 5.2 on 2025-04-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicebookings', '0007_rename_service_type_servicerecord_service_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerecord',
            old_name='service_type_id',
            new_name='service_type',
        ),
    ]
