# Generated by Django 5.2 on 2025-04-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicebookings', '0008_rename_service_type_id_servicerecord_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='service_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
