# Generated by Django 5.2 on 2025-04-28 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicebookings', '0009_servicerecord_service_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testdriverecord',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testdriverecord',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testdriverecord',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
