# Generated by Django 5.2 on 2025-04-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicebookings', '0010_servicerecord_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdriverecord',
            name='test_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='testdriverecord',
            name='test_notes',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
