# Generated by Django 5.2 on 2025-04-10 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_model_createdby_model_is_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.brand', verbose_name='brand name'),
        ),
        migrations.AlterField(
            model_name='model',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category', verbose_name='category'),
        ),
    ]
