# Generated by Django 5.2 on 2025-04-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_model_brand_alter_model_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='VehicleBrand',
        ),
        migrations.RenameModel(
            old_name='Model',
            new_name='VehicleModel',
        ),
    ]
