# Generated by Django 5.2 on 2025-04-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_brand_vehiclebrand_rename_model_vehiclemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiclebrand',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
