# Generated by Django 5.2 on 2025-04-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_category_description_vehiclebrand_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='assests/media/uploads/LX200.jpg', upload_to='uploads/Category/'),
            preserve_default=False,
        ),
    ]
