# Generated by Django 5.2 on 2025-04-22 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_feature_vehiclemodel_features_delete_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_brand', to='inventory.vehiclebrand'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_category', to='inventory.category'),
        ),
    ]
