# Generated by Django 5.2 on 2025-04-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_vehiclemodel_brand_alter_vehiclemodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='license_plate',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
