# Generated by Django 5.2 on 2025-04-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_vehiclemodel_license_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='license_plate',
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='vin_number',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
